### ISSUE TITLE
Parse github linked comments

### ISSUE THREAD

**Issue by SoniEx2** [maxpowa/inumuta-modules#16]
E.g. parse the # part on `https://github.com/OpenMods/OpenModsLib/issues/54#issuecomment-138061659`.

Then post only the linked comment.

**Comment by maxpowa** [comment]
Will do this eventually. I don't have a lot of time to work on Inumuta recently, just been doing bugfixes. Ya know, family and work and stuff like to take a lot of time.

**Comment by maxpowa** [comment]
```
<maxpowa> https://github.com/maxpowa/inumuta-modules/issues/16#issuecomment-138099266
<Inumuta> [Github] [maxpowa/inumuta-modules #16] maxpowa: Will do this eventually. I don't have a lot of time to work on Inumuta recently, just been doing bugfixes. Ya know, family and work and stuff like to take a lot of time.
```

**Comment by SoniEx2** [comment]
<+Soni> https://github.com/maxpowa/inumuta-modules/issues/16#issuecomment-146052759
    <+Inumuta> [Github] [maxpowa/inumuta-modules #16] maxpowa: ```...

(Altho I guess this is a separate issue...)

**Comment by maxpowa** [comment]
Well that's because the text was longer than one line, and the first line was ```. I truncate responses that are longer than one line to prevent Inumuta from spamming channels with tons of text.

**Comment by SoniEx2** [comment]
Concatenate lines.

**Comment by maxpowa** [comment]
I do usually, but github module makes a special exception to remove the following lines. I changed the behavior so now if the first line is less than 180 characters, it will include the second.
