### ISSUE TITLE
Parse redd.it

### ISSUE THREAD

**Issue by SoniEx2** [maxpowa/inumuta-modules#19]
e.g. https://redd.it/3nyo3a

**Comment by maxpowa** [comment]
~~This is because reddit's SSL cert only matches *.reddit.com and reddit.com. Python urllib does strict checking on hostnames in the cert and notices that redd.it isn't included, rejecting the request. I should be able to fix this when I switch to python 3, but for now it can't be fixed.~~

Due to SNI.

**Comment by SoniEx2** [comment]
Uhh but I don't get an SSL error with redd.it...

**Comment by maxpowa** [comment]
You don't get it in your browser because the browser handles the redirect differently from python.

**Comment by SoniEx2** [comment]
![Looks like you're wrong.](http://i.imgur.com/MjZzzJ8.png)

**Comment by maxpowa** [comment]
._.

`openssl s_client -showcerts -connect redd.it:443 </dev/null`

https://p.xpw.us/biface

**Comment by SoniEx2** [comment]
Uhh huh... How does that work?

**Comment by maxpowa** [comment]
~~It dumps the certificate information for connecting to a website. That's about as pure certificate information as you're ever going to get. There is absolutely no mention of redd.it as a Common Name (CN) for any of the certificates that are returned.~~

**Comment by SoniEx2** [comment]
How does the browser get the valid cert?

**Comment by maxpowa** [comment]
~~Looks like you're seeing a Gandi cert, so I'm guessing it's coming from Chrome's AddTrust External CA Root. Don't quote me on that though.~~

~~Edit: Mistyped. Meant Firefox, not Chrome. AddTrust is part of Comodo's reseller root certs.~~

**Comment by maxpowa** [comment]
GUESS WHAT I LIED ALL ALONG. Reddit uses fancy shit like SNI and sopel web.py didn't support it. Luckily someone's got a PR in for it and it should be fixed soon \o/

**Comment by roperi** [comment]
@maxpowa 

Was it fixed?

**Comment by maxpowa** [comment]
@h-2-0 your issue seems unrelated. This was due to Python 2.7's lack of support for SNI. If you want to be sure that your python version supports SNI, use the requests module and [its dependencies](http://stackoverflow.com/a/18579484).

**Comment by roperi** [comment]
Thanks, @maxpowa

**Comment by roperi** [comment]
@maxpowa 
Just for the sake of letting you know I downloaded requests' dependencies for python2.7 but still didn't work. It seems my issue is very unrelated. Thanks anyway for your help.
