### ISSUE TITLE
DCC CHAT support

### ISSUE THREAD

**Issue by SoniEx2** [maxpowa/inumuta-modules#21]
There should be a .dcc command that starts a DCC chat.

DCC chat doesn't have rate limiting.

**Comment by maxpowa** [comment]
Has been brought up in the sopel main repo in the past. (see https://github.com/sopel-irc/sopel/issues/115)

I am not interested in implementing it. If someone makes a module for it, I may consider adding it but I don't feel like spending a bunch of time writing a module that people are rarely going to use.
