### ISSUE TITLE
.tellat: .tell at a given time

### ISSUE THREAD

**Issue by SoniEx2** [maxpowa/inumuta-modules#23]
There should be a .tellat command which takes either a unix timestamp, an ISO 8601 timestamp or a relative unix timestamp and only allows the message to go through after the given time.

So e.g.

```
[Some given time] <SoniEx2> .tellat * +1000 This is a message
[...] <Inumuta> I'll pass that on when * is around.
[Some given time + 100] <SoniEx2> something
- no message from inumuta -
[Some given time + 1000] <SoniEx2> something
[...] <Inumuta> SoniEx2: Some given time <SoniEx2> This is a message
```

**Comment by maxpowa** [comment]
like `.in`?

**Comment by SoniEx2** [comment]
No because that's for self. .tellat would be for someone else.

**Comment by SoniEx2** [comment]
Also what happens if you use .in, and then /quit?

**Comment by maxpowa** [comment]
What's the use case for `.tellat` then, why would you want to prevent them from hearing something until after a given time?

**Comment by SoniEx2** [comment]
"I'm sorry"?

**Comment by SoniEx2** [comment]
Or a suicide note?

**Comment by maxpowa** [comment]
._. If that's your use case, that's pretty pathetic. You can't even be fucked to say sorry yourself so you have a bot say it for you?
