### ISSUE TITLE
Steam.py Agecheck

### ISSUE THREAD

**Issue by benjbubu** [maxpowa/inumuta-modules#9]
Certain games on Steam needs an age check. When you try to go to the URL of the game it redirects to an url like "http://store.steampowered.com/agecheck/app/XXXXX/". So bs4 can't parse anything on this page and the module returns "Can't find this game".

Any idea to bypass through this ?

**Comment by allout58** [comment]
You could claim to be old enought and get redirected back, but that requires more web page parsing...

**Comment by maxpowa** [comment]
I'm pretty sure I can simulate an age cookie. Should have a fix in a couple hours.

**Comment by maxpowa** [comment]
Tested with Huniepop; worked fine.

**Comment by benjbubu** [comment]
I confirm it's working. Great job.
